# Generated by Django 2.2.6 on 2019-10-10 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20191010_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='tw',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 10, 10, 15, 21, 0, 491111), max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date1_end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date1_start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date2_end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date2_start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date3_end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date3_start',
            field=models.CharField(default='', max_length=100),
        ),
    ]
