# Generated by Django 2.2.6 on 2019-10-12 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20191011_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='tw',
            name='date4_end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tw',
            name='date4_start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date',
            field=models.CharField(default=datetime.date(2019, 10, 12), max_length=100),
        ),
        migrations.AlterField(
            model_name='tw',
            name='date1_start',
            field=models.CharField(default=datetime.date(2019, 10, 19), max_length=100),
        ),
    ]
