# Generated by Django 2.2.6 on 2019-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twven', '0003_auto_20191010_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('taskNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
